name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Change directory to the root of the repository
        run: cd $GITHUB_WORKSPACE/iois-lpnu
      - name: Install dependencies
        run: npm install --prefix mantis-free-react-admin-template
      - name: Build
        run: npm run build --prefix mantis-free-react-admin-template
